# Parameters for supply chain pipeline
horizon: 1
lags:
  - 1
  - 7
  - 14
rolling_windows:
  - 7
  - 14
  - 28
anomaly_thresholds:
  z_score: 3.0
  iqr: 1.5
  missingness: 0.02  # 2% threshold for missing values
  date_gap_days: 1    # Maximum allowed gap in days
output_base_path: /opt/airflow/data
