name: Deploy Independent Foundation

on:
  push:
    branches: [main, rohit]
    paths:
      - "terraform/foundation/**"
      - "terraform/modules/**"
      - ".github/workflows/deploy-foundation.yml"
  workflow_dispatch:

env:
  GCP_REGION: us-central1
  ENVIRONMENT: prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set Project ID
        run: |
          PROJECT_ID=$(echo '${{ secrets.GCP_SA_KEY }}' | jq -r .project_id)
          echo "GCP_PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        working-directory: terraform/foundation
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/foundation
        run: |
          terraform apply -auto-approve \
            -var="project_id=${{ env.GCP_PROJECT_ID }}" \
            -var="region=${{ env.GCP_REGION }}" \
            -var="environment=${{ env.ENVIRONMENT }}" \
            -var="db_password=${{ secrets.TF_VAR_DB_PASSWORD }}" \
            -var="airflow_fernet_key=${{ secrets.TF_VAR_AIRFLOW_FERNET_KEY }}" \
            -var="airflow_jwt_secret=${{ secrets.TF_VAR_AIRFLOW_JWT_SECRET }}" \
            -var="mongo_uri=${{ secrets.TF_VAR_MONGO_URI }}" \
            -var="github_token=${{ secrets.TF_VAR_GITHUB_TOKEN }}"
